import type { errno } from "@/wasi/ty/mod.ts";

export const success = 0x00 as errno; // No error occurred. System call completed successfully.
export const _2big = 0x01 as errno; // Argument list too long.
export const acces = 0x02 as errno; // Permission denied.
export const addrinuse = 0x03 as errno; // Address in use.
export const addrnotavail = 0x04 as errno; // Address not available.
export const afnosupport = 0x05 as errno; // Address family not supported.
export const again = 0x06 as errno; // Resource unavailable, or operation would block.
export const already = 0x07 as errno; // Connection already in progress.
export const badf = 0x08 as errno; // Bad file descriptor.
export const badmsg = 0x09 as errno; // Bad message.
export const busy = 0x0A as errno; // Device or resource busy.
export const canceled = 0x0B as errno; // Operation canceled.
export const child = 0x0C as errno; // No child processes.
export const connaborted = 0x0D as errno; // Connection aborted.
export const connrefused = 0x0E as errno; // Connection refused.
export const connreset = 0x0F as errno; // Connection reset.
export const deadlk = 0x10 as errno; // Resource deadlock would occur.
export const destaddrreq = 0x11 as errno; // Destination address required.
export const dom = 0x12 as errno; // Mathematics argument out of domain of function.
export const dquot = 0x13 as errno; // Reserved.
export const exist = 0x14 as errno; // File exists.
export const fault = 0x15 as errno; // Bad address.
export const fbig = 0x16 as errno; // File too large.
export const hostunreach = 0x17 as errno; // Host is unreachable.
export const idrm = 0x18 as errno; // Identifier removed.
export const ilseq = 0x19 as errno; // Illegal byte sequence.
export const inprogress = 0x1A as errno; // Operation in progress.
export const intr = 0x1B as errno; // Interrupted function.
export const inval = 0x1C as errno; // Invalid argument.
export const io = 0x1D as errno; // I/O error.
export const isconn = 0x1E as errno; // Socket is connected.
export const isdir = 0x1F as errno; // Is a directory.
export const loop = 0x20 as errno; // Too many levels of symbolic links.
export const mfile = 0x21 as errno; // File descriptor value too large.
export const mlink = 0x22 as errno; // Too many links.
export const msgsize = 0x23 as errno; // Message too large.
export const multihop = 0x24 as errno; // Reserved.
export const nametoolong = 0x25 as errno; // Filename too long.
export const netdown = 0x26 as errno; // Network is down.
export const netreset = 0x27 as errno; // Connection aborted by network.
export const netunreach = 0x28 as errno; // Network unreachable.
export const nfile = 0x29 as errno; // Too many files open in system.
export const nobufs = 0x2A as errno; // No buffer space available.
export const nodev = 0x2B as errno; // No such device.
export const noent = 0x2C as errno; // No such file or directory.
export const noexec = 0x2D as errno; // Executable file format error.
export const nolck = 0x2E as errno; // No locks available.
export const nolink = 0x2F as errno; // Reserved.
export const nomem = 0x30 as errno; // Not enough space.
export const nomsg = 0x31 as errno; // No message of the desired type.
export const noprotoopt = 0x32 as errno; // Protocol not available.
export const nospc = 0x33 as errno; // No space left on device.
export const nosys = 0x34 as errno; // Function not supported.
export const notconn = 0x35 as errno; // The socket is not connected.
export const notdir = 0x36 as errno; // Not a directory or a symbolic link to a directory.
export const notempty = 0x37 as errno; // Directory not empty.
export const notrecoverable = 0x38 as errno; // State not recoverable.
export const notsock = 0x39 as errno; // Not a socket.
export const notsup = 0x3A as errno; // Not supported, or operation not supported on socket.
export const notty = 0x3B as errno; // Inappropriate I/O control operation.
export const nxio = 0x3C as errno; // No such device or address.
export const overflow = 0x3D as errno; // Value too large to be stored in data type.
export const ownerdead = 0x3E as errno; // Previous owner died.
export const perm = 0x3F as errno; // Operation not permitted.
export const pipe = 0x40 as errno; // Broken pipe.
export const proto = 0x41 as errno; // Protocol error.
export const protonosupport = 0x42 as errno; // Protocol not supported.
export const prototype = 0x43 as errno; // Protocol wrong type for socket.
export const range = 0x44 as errno; // Result too large.
export const rofs = 0x45 as errno; // Read-only file system.
export const spipe = 0x46 as errno; // Invalid seek.
export const srch = 0x47 as errno; // No such process.
export const stale = 0x48 as errno; // Reserved.
export const timedout = 0x49 as errno; // Connection timed out.
export const txtbsy = 0x4A as errno; // Text file busy.
export const xdev = 0x4B as errno; // Cross-device link.
export const notcapable = 0x4C as errno; // Extension: Capabilities insufficient.
